name: Publish

on:
  workflow_dispatch:
    inputs:
      libraryVersion:
        description: "Version to publish (e.g. 1.7.0)"
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Publish to github packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish -PlibraryVersion="${{ inputs.libraryVersion }}"
